-- liquibase formatted sql

-- changeset reinner:1698006075957-1
CREATE TABLE calculation_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    execution_time TIMESTAMP(6) WITHOUT TIME ZONE,
    first_num VARCHAR(255),
    first_num_system INTEGER,
    operation VARCHAR(255),
    result VARCHAR(255),
    second_num VARCHAR(255),
    second_num_system INTEGER,
    CONSTRAINT "calculation_resultPK" PRIMARY KEY (id)
                                );

